[18.0][MIG] product_template_multi_link: Migration to 18.0
thienvh332/e-commerce pull request #1
Opened 2024-11-28 09:39 UTC by thienvh332

### Blacklist:
- `#800`

### Changes:
- Delete name_search. Because it is no longer needed. (see https://github.com/odoo/odoo/pull/174967/commits/9e21ec27efb2dd2bcbb2d8fc1e0e2bad6ca8d62d#diff-35eeb9b2264b76eca30fcb0a923757dde3ca14c636ce6faf66ef31a6b649799bR539)

2024-12-04 08:32 UTC, nguyenminhchien requested changes

2024-12-04 08:32 UTC, nguyenminhchien commented on product_template_multi_link/models/product_template.py
> +            "name": _("Product links"),
```suggestion
            "name": self.env._("Product links"),
```

2024-12-04 08:32 UTC, nguyenminhchien commented on product_template_multi_link/models/product_template_link.py
> +                _("You can only create a link between 2 different products")
```suggestion
                self.env._("You can only create a link between 2 different products")
```

2024-12-04 08:32 UTC, nguyenminhchien commented on product_template_multi_link/models/product_template_link.py
> +                _(
```suggestion
                self.env._(
```

2024-12-04 08:32 UTC, nguyenminhchien commented on product_template_multi_link/models/product_template.py
> +    def _search_display_name(self, operator, value):
no need to override this method.
def _search_display_name() is different from def name_search().

Remove the context `name_search_default_code` from the view as well.

2024-12-04 08:32 UTC, nguyenminhchien commented on product_template_multi_link/models/product_template_link.py
> +        string="Right Product Image", related="right_product_tmpl_id.image_128"
```
2024-12-04 07:07:57,750 148504 WARNING v18c_product_template_multi_link odoo.addons.base.models.ir_model: Two fields (right_product_img, left_product_img) of product.template.link() have the same label: Image 128. [Modules: product_template_multi_link and product_template_multi_link]
```

2024-12-04 08:32 UTC, nguyenminhchien commented on product_template_multi_link/models/product_template_link.py
```
2024-12-04 08:21:19,556 148504 INFO v18c_product_template_multi_link werkzeug: 127.0.0.1 - - [04/Dec/2024 08:21:19] "POST /web/dataset/call_kw/product.template.link/onchange HTTP/1.1" 200 - 2 0.002 0.007
2024-12-04 08:21:20,172 148504 ERROR v18c_product_template_multi_link odoo.osv.expression: Non-stored field product.template.link.type.display_name cannot be searched. 
NoneType: None
```

2024-12-04 08:32 UTC, nguyenminhchien commented on product_template_multi_link/views/product_template_link_view.xml
> +            <kanban>
Kanban view is broken.
![image](https://github.com/user-attachments/assets/ae6b4885-c407-4ef1-b083-78196d50b15f)

2024-12-04 09:08 UTC, thienvh332 commented
Hi @nguyenminhchien ,
- I'm not sure what's going on your side. The errors you had I fixed a long time ago and I don't see them locally. If it happens again let me know.
> Remove the context name_search_default_code from the view as well.

- In my opinion, to avoid affecting the search results of other flows, we still need context here. What do you think?

2024-12-04 10:54 UTC, nguyenminhchien commented
> Hi @nguyenminhchien ,
> 
>     * I'm not sure what's going on your side. The errors you had I fixed a long time ago and I don't see them locally. If it happens again let me know.
> 
> 
> > Remove the context name_search_default_code from the view as well.
> 
>     * In my opinion, to avoid affecting the search results of other flows, we still need context here. What do you think?

Could you please give me a case which triggers this search? @thienvh332

2024-12-04 11:02 UTC, thienvh332 commented
Hi @nguyenminhchien : [Link testcase](https://github.com/thienvh332/e-commerce/blob/18.0-mig-product_template_multi_link/product_template_multi_link/tests/test_product_template.py#L40)

2024-12-04 11:05 UTC, nguyenminhchien commented
> Hi @nguyenminhchien : [Link testcase](https://github.com/thienvh332/e-commerce/blob/18.0-mig-product_template_multi_link/product_template_multi_link/tests/test_product_template.py#L40)

Let me correct myself, i means "user case" not "test case".
I want a user case in 18.0 which triggers it.

2024-12-04 11:18 UTC, thienvh332 commented
We cannot have this case in UI because **`name_search`** will not pass condition **`args[0][0] == "id"`** which will make "if" false and this case will not be triggered
![image](https://github.com/user-attachments/assets/2bd297a6-a0d1-4359-9db7-a6dd72697949)

2024-12-04 11:25 UTC, thienvh332 commented
We can consider allowing search with `default_code` without `id != 0` condition when there is context `name_search_default_code`. What do you think?

2024-12-05 10:02 UTC, nguyenminhchien requested changes
If you remove name_search.
You should not port the commit ` pt_multi_link: improve UX by searching templates on default_code `. But, add it to ignore list, instead.

2024-12-06 03:48 UTC, nguyenminhchien approved these changes

2024-12-06 04:13 UTC, closed without merging